### ISSUE TITLE
xmlrunner interferes with subprocess use of sys.stderr

### ISSUE THREAD

**Issue by whitty** [xmlrunner/unittest-xml-reporting#194]
Switching from `unittest` to `xmlrunner` is breaking calls to `subprocess` which pass `sys.stderr`

Example reproduction:

```python
import unittest
import sys
import subprocess

class SubprocessStderr(unittest.TestCase):

    def test_stderr(self):
        proc = subprocess.Popen(["ls","/doesnot_exist", "/"], stderr=sys.stderr, stdout=subprocess.PIPE)
        out = proc.communicate()
        self.assertTrue(len(out[0]) > 0)
```

Passes with `python -m unittest discover` fails with `python -m xmlrunner discover` as follows:

```
Traceback (most recent call last):
  File "/home/greg/work/libcommon/lib/unittest-xml-reporting/tests/test_subprocess_stderr.py", line 8, in test_stderr
    proc = subprocess.Popen(["ls","/doesnot_exist", "/"], stderr=sys.stderr, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 703, in __init__
    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python2.7/subprocess.py", line 1153, in _get_handles
    errwrite = stderr.fileno()
UnsupportedOperation: fileno
```

**Comment by jakecobb** [comment]
Came to report the same problem with `sys.stdout`.  It seems the standard i/o are wrapped in a `xmlrunner.result._DuplicateWriter`.

**Comment by dnozay** [comment]
You can either create your own file-like object and pass that in your tests; or save `sys.stdout` and `sys.stderr` as a global and use that in the tests.

This is expected behavior as the output is saved for the xml results.

**Comment by jakecobb** [comment]
@dnozay The way I came across this behavior is because by default all the output from `subprocess.run`/`subprocess.Popen` goes to the test process standard out/err, but the xml runner fails to capture this output because it is only overriding the `sys.stdout` and `sys.stderr` references in Python.  Explicitly passing `sys.stdout` and `sys.stderr` is the obvious next step but the wrapper fails in this regard as reported in this bug.  Saving the original `sys.stdout` and passing that puts us back at the first problem.

In @whitty 's example the `subprocess` call is right in the test and could be re-written to use `subprocess.PIPE` and `communicate()`, or else a small mess of threading code to do it asynchronously, but in general the `subprocess` calls could be anywhere in the code under test.

**Comment by dnozay** [comment]
If you don't care about the output:

```python
import sys

ORIGINAL_STDOUT = sys.stdout
ORIGINAL_STDERR = sys.stderr

class TestThatUsesSubprocess(unittest.TestCase):
    def test_something(self):
         # replace stuff unittest-xml-reporting replaced.
         sys.stdout, sys.stderr = ORIGINAL_STDOUT, ORIGINAL_STDERR
         # ... regular test code ...
         pass
```

> In @whitty 's example the subprocess call is right in the test and could be re-written to use subprocess.PIPE and communicate(), or else a small mess of threading code to do it asynchronously, but in general the subprocess calls could be anywhere in the code under test.

if you do care about the output, then your test would need to replace `sys.stdout` and `sys.stderr` and use pipes, i'm choosing not to include that in this package as this is tricky to get right and not hang.

**Comment by mbUSC** [comment]
I encountered the same problem
